# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailflow" do
  name "tailflow"
  desc "TailFlow workflow engine"
  homepage "https://github.com/tailflowio/tailflow-agent"
  version "2026.9.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailflow"

  on_macos do
    on_intel do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_darwin_amd64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "ece2f25ee70194b91f91f23de9c297c5ba92b70e5c40d76f283908b3d3b2dc83"
    end
    on_arm do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_darwin_arm64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "0bd9c5db10029407507a123194e7d955aad51a1b2532b4cc7a2824e27cc1ffec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_linux_amd64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "4ff3e552d62e1471b3322c1b3560c59670d2276559a0d0f1c672f62d73e3ae42"
    end
    on_arm do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_linux_arm64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "317a36af9e1cf118458b91579a8770ff4fc8c1ab5dde57858f772a50d25bdd79"
    end
  end

  # No zap stanza required
end
