# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailflow" do
  name "tailflow"
  desc "TailFlow workflow engine"
  homepage "https://github.com/tailflowio/tailflow-agent"
  version "2026.9.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailflow"

  on_macos do
    on_intel do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_darwin_amd64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "0a5ec1e17d417c40c3872ce62e640663c33e40a9f6ffeaa2ed00eb4ab488d8c9"
    end
    on_arm do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_darwin_arm64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "d6808f1ff137dc8d3ada61822863370ff0e68e8ae4152399e4512dfe93f2ac66"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_linux_amd64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "c05bc104bc9be42c3fc83f400da2f17b4c3c4933bad6563b01b3617edd5ae095"
    end
    on_arm do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_linux_arm64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "cd9743b9b85e4b4ff903b8b5d3b7a0a8a338566f518e67f926f5030833f75d3d"
    end
  end

  # No zap stanza required
end
