# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailflow" do
  name "tailflow"
  desc "TailFlow workflow engine"
  homepage "https://github.com/tailflowio/tailflow-agent"
  version "2026.10.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailflow"

  on_macos do
    on_intel do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_darwin_amd64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "45db5bd6abcbb7826334b2fa2116550778cf118f495b28f78435654b1c23b472"
    end
    on_arm do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_darwin_arm64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "2a67e09ce7a5e5efa1d7bbf11c78b13b20ac623c85ee4cddb2dc445469be2fb1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_linux_amd64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "e401b1c944ba821f99ab44da3f918aa2a5c632fbce99822df603fe4a969974af"
    end
    on_arm do
      url "https://github.com/tailflowio/tailflow-agent/releases/download/#{version}/tailflow-agent_linux_arm64.tar.gz",
        verified: "github.com/tailflowio/tailflow-agent"
      sha256 "9e45d73befb96888d342cd811b2903fe1822a6da01f5fdb5e029dec7f93e111f"
    end
  end

  # No zap stanza required
end
