# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TailflowAgent < Formula
  desc "TailFlow workflow engine"
  homepage "https://github.com/tailflowio/tailflow-agent"
  version "2026.9.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tailflowio/tailflow-agent/releases/download/2026.9.4/tailflow-agent_darwin_amd64.tar.gz"
      sha256 "ceaf2cfdce753980eed8bf3df4dc44fa1ec9dd0ea5016b4668440b52db0bd45a"

      define_method(:install) do
        bin.install "tailflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tailflowio/tailflow-agent/releases/download/2026.9.4/tailflow-agent_darwin_arm64.tar.gz"
      sha256 "eed312f30c112c75a62b296bff2f1c08267743c449f6735431c2469f50c0f6c3"

      define_method(:install) do
        bin.install "tailflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tailflowio/tailflow-agent/releases/download/2026.9.4/tailflow-agent_linux_amd64.tar.gz"
      sha256 "78931f43d0f1953b03123ba44b2474f057aa28a8ddb522270845ce76d6cbbd85"
      define_method(:install) do
        bin.install "tailflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tailflowio/tailflow-agent/releases/download/2026.9.4/tailflow-agent_linux_arm64.tar.gz"
      sha256 "83a64d808cd1fbb83161d1011b2f493bade368103f4549911c0162e81c5a2ede"
      define_method(:install) do
        bin.install "tailflow"
      end
    end
  end

  test do
    system "#{bin}/tailflow", "--version"
  end
end
